/**
 * Build a self-contained deployment bundle for Hostinger (and any Node host).
 *
 * Output: ./deploy
 *   app.js            single-file CommonJS bundle of the whole API + packages
 *   public/           landing + dashboard static assets (served by the app)
 *   public/docs, Specs.md, proje.md, docker/   referenced docs (so nav links resolve)
 *   package.json      minimal, `npm start` → node app.js
 *   .env.example      production env template
 *   README.md         upload instructions
 *
 * Puppeteer is left external (optional); on shared hosting it is simply absent and the engine
 * falls back to the pure-JS structured renderer.
 */
import { build } from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const deploy = path.join(root, "deploy");
const publicDir = path.join(deploy, "public");

// ---- clean ----
fs.rmSync(deploy, { recursive: true, force: true });
fs.mkdirSync(publicDir, { recursive: true });

// ---- bundle the API ----
await build({
  entryPoints: [path.join(root, "apps/api/src/main.ts")],
  outfile: path.join(deploy, "app.js"),
  bundle: true,
  platform: "node",
  target: "node18",
  format: "cjs",
  legalComments: "none",
  external: ["puppeteer"], // optional, resolved at runtime if present
  banner: { js: "/* AeroPDF.dev — bundled server. Generated by scripts/build-deploy.mjs */" },
  logLevel: "info",
});

// ---- copy static assets ----
const copy = (from, to) => {
  const src = path.join(root, from);
  if (fs.existsSync(src)) fs.cpSync(src, path.join(deploy, to), { recursive: true });
};
copy("apps/dashboard", "public");
copy("docs", "public/docs");
copy("Specs.md", "public/Specs.md");
copy("proje.md", "public/proje.md");
copy("docker", "public/docker");

// ---- deploy package.json (no runtime deps: everything is bundled) ----
fs.writeFileSync(
  path.join(deploy, "package.json"),
  JSON.stringify(
    {
      name: "aeropdf-deploy",
      version: "0.1.0",
      private: true,
      description: "AeroPDF.dev production bundle",
      main: "app.js",
      scripts: { start: "node app.js" },
      engines: { node: ">=18" },
    },
    null,
    2,
  ) + "\n",
);

// ---- env template ----
fs.writeFileSync(
  path.join(deploy, ".env.example"),
  [
    "# AeroPDF.dev production env",
    "PORT=8080",
    "HOST=0.0.0.0",
    "AEROPDF_API_KEY=change-this-to-a-long-random-string",
    "STORAGE_DRIVER=local",
    "STORAGE_PATH=./data",
    "DASHBOARD_DIR=./public",
    "MAX_UPLOAD_MB=50",
    "ENABLE_HTML_PDF=off",
    "",
  ].join("\n"),
);

// ---- README ----
fs.writeFileSync(
  path.join(deploy, "README.md"),
  `# AeroPDF.dev — production bundle

Self-contained build. Start with:

    DASHBOARD_DIR=./public STORAGE_PATH=./data node app.js

On Hostinger hPanel Node.js app set the **startup file** to \`app.js\` and add the env vars from
\`.env.example\` (especially a strong \`AEROPDF_API_KEY\`). See ../DEPLOY.md for full steps.
`,
);

console.log("\n✓ deploy/ ready");
console.log("  - app.js (bundled)");
console.log("  - public/ (landing + dashboard + docs)");
console.log("  - package.json, .env.example, README.md");
